contact_links:
- name: ğŸ“ƒ Documentation Issue
  url: https://github.com/framework7io/framework7-website/issues/new
  about: Issues with documentation or website
- name: âš™ï¸ CLI Issue
  url: https://github.com/framework7io/framework7-cli/issues/new
  about: Issues with Framework7 CLI
